//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Xenosynth.Modules.Cms.Admin {
    
    public partial class DeletedFiles {
        protected Xenosynth.Admin.Content.SearchFiles SearchFiles1;
        protected Xenosynth.Modules.Cms.Admin.Controls.RecentFileTasks RecentFileTasks;
        protected Xenosynth.Admin.Controls.MessageBox MessageBox1;
        protected System.Web.UI.WebControls.DataGrid DataGridFiles;
        protected System.Web.UI.WebControls.LinkButton ButtonRestoreSelected;
        protected Fluent.AlertButton Alertbutton3;
        protected System.Web.UI.WebControls.LinkButton ButtonDeleteSelected;
        protected Fluent.AlertButton Alertbutton4;
        protected Fluent.EmptyRepeaterPanel.EmptyRepeaterPanel Emptyrepeaterpanel2;
        protected Fluent.DataGridAdapter DataGridAdapterFiles;
    }
}
