//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Xenosynth.Admin.Content {
    
    public partial class MoveFile {
        protected System.Web.UI.WebControls.PlaceHolder PlaceHolderAction;
        protected System.Web.UI.WebControls.RadioButtonList RadioButtonListAction;
        protected System.Web.UI.WebControls.TextBox TextBoxFileName;
        protected System.Web.UI.WebControls.RequiredFieldValidator Requiredfieldvalidator1;
        protected System.Web.UI.WebControls.RegularExpressionValidator RegularExpressionValidatorFileName;
        protected System.Web.UI.WebControls.DropDownList DropDownListDirectories;
        protected System.Web.UI.WebControls.Button Button1;
        protected System.Web.UI.WebControls.Button Button2;
        protected Fluent.DataBinding.DataBindingManager DataBindingManagerFile;
    }
}
