//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Xenosynth.Modules.Cms.Admin {
    
    public partial class SlidePanel {
        protected System.Web.UI.WebControls.Panel SidePanel;
        protected System.Web.UI.WebControls.PlaceHolder SidePanelPlaceHolder;
        protected System.Web.UI.WebControls.Image ImageSlider;
        protected System.Web.UI.WebControls.PlaceHolder MainPanelPlaceHolder;
        protected AjaxControlToolkit.CollapsiblePanelExtender CollapsiblePanelExtenderSidePanel;
    }
}
