//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Xenosynth.Modules.Cms.Admin.Controls {
    
    public partial class EditFileAttributes {
        protected System.Web.UI.WebControls.DataGrid DataGridAttributes;
        protected Fluent.EmptyRepeaterPanel.EmptyRepeaterPanel Emptyrepeaterpanel2;
        protected System.Web.UI.WebControls.LinkButton ButtonSave;
        protected System.Web.UI.WebControls.TextBox TextBoxName;
        protected System.Web.UI.WebControls.TextBox TextBoxValue;
        protected System.Web.UI.WebControls.Button Button1;
        protected System.Web.UI.WebControls.Button Button2;
        protected Fluent.DataBinding.DataBindingManager DataBindingManagerAttribute;
    }
}
