//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Xenosynth.Admin.Tools {
    
    public partial class GoogleSitemap {
        protected System.Web.UI.HtmlControls.HtmlForm Form1;
        protected Fluent.Presentation.Template TemplateLayout1;
        protected Fluent.Presentation.TemplateSection Side;
        protected Xenosynth.Admin.Tools.ToolTasks Tooltasks1;
        protected Fluent.Presentation.TemplateSection Main;
        protected System.Web.UI.WebControls.DropDownList DropDownListHostHeader;
        protected System.Web.UI.WebControls.Button Button2;
    }
}
