//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Xenosynth.Admin.Resources {
    
    public partial class AddResource {
        
        protected System.Web.UI.HtmlControls.HtmlForm Form1;
        protected Fluent.Presentation.Template TemplateLayout1;
        protected Fluent.Presentation.TemplateSection Side;
        protected Xenosynth.Admin.Resources.ResourceTasks ResourceTasks;
        protected Fluent.Presentation.TemplateSection Main;
        protected System.Web.UI.WebControls.TextBox TextBoxName;
        protected System.Web.UI.WebControls.TextBox TextBoxCategory;
        protected System.Web.UI.WebControls.TextBox TextBoxDescription;
        protected System.Web.UI.WebControls.TextBox TextBoxDescriptionCount;
        protected Fluent.MultiLineTextBoxValidator Multilinetextboxvalidator2;
        protected System.Web.UI.WebControls.TextBox TextBoxValue;
        protected System.Web.UI.WebControls.TextBox TextBoxValueCount;
        protected Fluent.MultiLineTextBoxValidator Multilinetextboxvalidator1;
        protected System.Web.UI.WebControls.Button Button1;
        protected Fluent.DataBinding.DataBindingManager DataBindingManagerResource;
    }
}
