//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Xenosynth.Admin.Resources {
    
    public partial class _Default {
        
        protected System.Web.UI.HtmlControls.HtmlForm Form1;
        protected Fluent.Presentation.Template TemplateLayout1;
        protected Fluent.Presentation.TemplateSection Side;
        protected Fluent.Presentation.TemplateSection Main;
        protected System.Web.UI.WebControls.DataGrid DataGridResources;
        protected Fluent.EmptyRepeaterPanel.EmptyRepeaterPanel Emptyrepeaterpanel1;
        protected Fluent.DataGridAdapter DataGridAdapterResources;
    }
}
