// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace Xenosynth.Admin.Security {
	
	
	public partial class AddUser {
		
		protected System.Web.UI.WebControls.Content Content1;
		
		protected Xenosynth.Admin.Controls.MessageBox MessageBox1;
		
		protected Xenosynth.Admin.Security.UserTabControl UserTabControl1;
		
		protected System.Web.UI.WebControls.TextBox TextBoxUserName;
		
		protected System.Web.UI.WebControls.RequiredFieldValidator RequiredFieldValidator1;
		
		protected System.Web.UI.WebControls.TextBox TextBoxPassword;
		
		protected System.Web.UI.WebControls.RequiredFieldValidator RequiredFieldValidator3;
		
		protected System.Web.UI.WebControls.TextBox TextBoxEmail;
		
		protected System.Web.UI.WebControls.RequiredFieldValidator RequiredFieldValidator2;
		
		protected System.Web.UI.WebControls.TextBox TextBoxComment;
		
		protected System.Web.UI.WebControls.TextBox TextBoxCommentCount;
		
		protected Fluent.MultiLineTextBoxValidator Multilinetextboxvalidator2;
		
		protected System.Web.UI.WebControls.CheckBox CheckBoxIsApproved;
		
		protected System.Web.UI.WebControls.Button Button1;
		
		protected System.Web.UI.WebControls.Button Button2;
		
		protected Fluent.DataBinding.DataBindingManager DataBindingManagerUser;
		
		protected System.Web.UI.WebControls.Content Content2;
		
		protected Xenosynth.Admin.Users.UserTasks UserTasks1;
		
		protected Xenosynth.Admin.Security.SearchUsers SearchUsers1;
	}
}
