// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace Xenosynth.Admin.Users {
	
	
	public partial class Default {
		
		protected System.Web.UI.WebControls.Content Content1;
		
		protected Xenosynth.Admin.Users.UserTasks UserTasks1;
		
		protected Xenosynth.Admin.Security.SearchUsers SearchUsers1;
		
		protected System.Web.UI.WebControls.Content Content2;
		
		protected System.Web.UI.WebControls.DataGrid DataGridUsers;
		
		protected System.Web.UI.WebControls.HyperLink Hyperlink2;
		
		protected System.Web.UI.WebControls.LinkButton DeleteTemplateButton;
		
		protected Fluent.AlertButton Alertbutton1;
	}
}
