// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace Xenosynth.Admin.Security {
	
	
	public partial class EditPermissionRoles {
		
		protected System.Web.UI.WebControls.Content Content1;
		
		protected Xenosynth.Admin.Controls.MessageBox MessageBox1;
		
		protected Xenosynth.Admin.Controls.PathBrowser PathBrowser1;
		
		protected Xenosynth.Admin.Security.PermissionTabControl PermissionTabControl;
		
		protected System.Web.UI.WebControls.DataGrid DataGridRoles;
		
		protected System.Web.UI.WebControls.HiddenField HiddenFieldRole;
		
		protected System.Web.UI.WebControls.CheckBox CheckBoxRoleHasPermission;
		
		protected System.Web.UI.WebControls.Button Button1;
		
		protected System.Web.UI.WebControls.Content Content2;
		
		protected Xenosynth.Admin.Security.PermissionTasks PermissionTasks1;
	}
}
