// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace Xenosynth.Admin.Security {
	
	
	public partial class EditPermission {
		
		protected System.Web.UI.WebControls.Content Content1;
		
		protected Xenosynth.Admin.Controls.PathBrowser PathBrowser1;
		
		protected Xenosynth.Admin.Security.PermissionTabControl PermissionTabControl;
		
		protected System.Web.UI.WebControls.TextBox TextBoxKey;
		
		protected System.Web.UI.WebControls.RequiredFieldValidator RequiredFieldValidator1;
		
		protected System.Web.UI.WebControls.CustomValidator CustomValidator1;
		
		protected System.Web.UI.WebControls.TextBox TextBoxName;
		
		protected System.Web.UI.WebControls.TextBox TextBoxDescription;
		
		protected System.Web.UI.WebControls.TextBox TextBoxCategory;
		
		protected System.Web.UI.WebControls.Button Button1;
		
		protected System.Web.UI.WebControls.Button Button2;
		
		protected Fluent.DataBinding.DataBindingManager DataBindingManagerPermission;
		
		protected System.Web.UI.WebControls.Content Content2;
		
		protected Xenosynth.Admin.Security.PermissionTasks PermissionTasks1;
	}
}
