// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace Xenosynth.Admin.Security {
	
	
	public partial class EditRole {
		
		protected System.Web.UI.WebControls.Content Content1;
		
		protected Xenosynth.Admin.Security.RoleTasks RoleTasks1;
		
		protected System.Web.UI.WebControls.Content Content2;
		
		protected Xenosynth.Admin.Controls.MessageBox MessageBox1;
		
		protected Xenosynth.Admin.Controls.PathBrowser PathBrowser1;
		
		protected System.Web.UI.WebControls.DataGrid DataGridUsers;
		
		protected System.Web.UI.WebControls.HyperLink HyperLink1;
		
		protected System.Web.UI.WebControls.HiddenField HiddenFieldUser;
		
		protected System.Web.UI.WebControls.CheckBox CheckBoxUserInRole;
		
		protected System.Web.UI.WebControls.Button Button1;
	}
}
