// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace Xenosynth.Admin.Security {
	
	
	public partial class ViewPermissions {
		
		protected Xenosynth.Admin.Security.PermissionTasks PermissionTasks1;
		
		protected Xenosynth.Admin.Controls.MessageBox MessageBox1;
		
		protected System.Web.UI.WebControls.DataGrid DataGridPermissions;
		
		protected System.Web.UI.WebControls.HyperLink HyperLink1;
		
		protected System.Web.UI.WebControls.LinkButton DeleteButton;
		
		protected Fluent.AlertButton Alertbutton1;
		
		protected Fluent.EmptyRepeaterPanel.EmptyRepeaterPanel Emptyrepeaterpanel1;
		
		protected Fluent.DataGridAdapter DataGridAdapterPermissions;
	}
}
