// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace Xenosynth.Admin.Security {
	
	
	public partial class ViewRoles {
		
		protected System.Web.UI.WebControls.Content Content2;
		
		protected System.Web.UI.WebControls.Content Content1;
		
		protected Xenosynth.Admin.Controls.MessageBox MessageBox1;
		
		protected System.Web.UI.WebControls.DataGrid DataGridRoles;
		
		protected System.Web.UI.WebControls.LinkButton DeleteTemplateButton;
		
		protected Fluent.AlertButton Alertbutton1;
	}
}
