// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace Xenosynth.Admin.Security {
	
	
	public partial class SearchUsers {
		
		protected System.Web.UI.WebControls.TextBox TextBoxUserName;
		
		protected Fluent.AutoPostBack Autopostback1;
		
		protected System.Web.UI.WebControls.TextBox TextBoxEmail;
		
		protected Fluent.AutoPostBack Autopostback2;
		
		protected System.Web.UI.WebControls.Button ButtonSearch;
	}
}
