// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace Xenosynth.Admin.Security {
	
	
	public partial class ViewUserHistory {
		
		protected System.Web.UI.WebControls.Content Content1;
		
		protected Xenosynth.Admin.Controls.PathBrowser PathBrowser1;
		
		protected Xenosynth.Admin.Security.UserTabControl UserTabControl1;
		
		protected System.Web.UI.WebControls.DataGrid DataGridAuditLog;
		
		protected Fluent.EmptyRepeaterPanel.EmptyRepeaterPanel Emptyrepeaterpanel2;
		
		protected Fluent.DataGridAdapter DataGridAdapterAuditLog;
		
		protected System.Web.UI.WebControls.Content Content2;
		
		protected Xenosynth.Admin.Users.UserTasks UserTasks1;
		
		protected Xenosynth.Admin.Security.SearchUsers SearchUsers1;
	}
}
