// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace Xenosynth.Admin.Controls {
	
	
	public partial class SlidePanel {
		
		protected System.Web.UI.WebControls.Panel SidePanel;
		
		protected System.Web.UI.WebControls.PlaceHolder SidePanelPlaceHolder;
		
		protected System.Web.UI.WebControls.Image ImageSlider;
		
		protected System.Web.UI.WebControls.PlaceHolder MainPanelPlaceHolder;
		
		protected AjaxControlToolkit.CollapsiblePanelExtender CollapsiblePanelExtenderSidePanel;
	}
}
