// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace Xenosynth.Admin.Controls.WebParts {
	
	
	public partial class UsersOnline {
		
		protected System.Web.UI.WebControls.DataGrid DataGridUsers;
	}
}
