//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Xenosynth.Modules.Cms.Admin.Tools {
    
    public partial class ExcelImportTool {
        protected System.Web.UI.HtmlControls.HtmlInputFile InputFileUpload;
        protected System.Web.UI.WebControls.DropDownList DropDownListTemplates;
        protected System.Web.UI.WebControls.RequiredFieldValidator Requiredfieldvalidator2;
        protected System.Web.UI.WebControls.DropDownList DropDownListDirectories;
        protected System.Web.UI.WebControls.Button Button1;
        protected System.Web.UI.WebControls.Button Button2;
    }
}
