// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace Xenosynth.Admin.Configuration {
	
	
	public partial class AddModule {
		
		protected System.Web.UI.WebControls.TextBox TextBoxName;
		
		protected System.Web.UI.WebControls.TextBox TextBoxDescription;
		
		protected System.Web.UI.WebControls.TextBox TextBoxDescriptionCount;
		
		protected Fluent.MultiLineTextBoxValidator Multilinetextboxvalidator1;
		
		protected System.Web.UI.WebControls.TextBox TextBoxResourceFolder;
		
		protected System.Web.UI.WebControls.TextBox TextBoxClassName;
		
		protected System.Web.UI.WebControls.TextBox TextBoxInitOrder;
		
		protected System.Web.UI.WebControls.Button Button1;
		
		protected System.Web.UI.WebControls.Button Button2;
		
		protected Fluent.DataBinding.DataBindingManager DataBindingManagerModule;
	}
}
