// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace Xenosynth.Admin.Configuration {
	
	
	public partial class AddSetting {
		
		protected System.Web.UI.WebControls.Content Content1;
		
		protected System.Web.UI.WebControls.TextBox TextBoxKey;
		
		protected System.Web.UI.WebControls.RequiredFieldValidator RequiredFieldValidator3;
		
		protected System.Web.UI.WebControls.TextBox TextBoxCategory;
		
		protected System.Web.UI.WebControls.RequiredFieldValidator RequiredFieldValidator4;
		
		protected System.Web.UI.WebControls.TextBox TextBoxName;
		
		protected System.Web.UI.WebControls.RequiredFieldValidator RequiredFieldValidator1;
		
		protected System.Web.UI.WebControls.TextBox TextBoxDescription;
		
		protected System.Web.UI.WebControls.TextBox TextBoxDescriptionCount;
		
		protected Fluent.MultiLineTextBoxValidator Multilinetextboxvalidator1;
		
		protected System.Web.UI.WebControls.TextBox TextBoxType;
		
		protected System.Web.UI.WebControls.RequiredFieldValidator RequiredFieldValidator2;
		
		protected System.Web.UI.WebControls.TextBox TextBoxValue;
		
		protected System.Web.UI.WebControls.TextBox TextBoxValueCount;
		
		protected Fluent.MultiLineTextBoxValidator Multilinetextboxvalidator2;
		
		protected System.Web.UI.WebControls.Content Content2;
	}
}
