// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace Xenosynth.Admin.Configuration {
	
	
	public partial class Cache {
		
		protected System.Web.UI.WebControls.Content Content1;
		
		protected System.Web.UI.WebControls.DataGrid DataGridFileCache;
		
		protected System.Web.UI.WebControls.LinkButton DeleteCacheButton;
		
		protected Fluent.AlertButton Alertbutton1;
		
		protected Fluent.EmptyRepeaterPanel.EmptyRepeaterPanel Emptyrepeaterpanel1;
		
		protected System.Web.UI.WebControls.Content Content2;
	}
}
