//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Xenosynth.Admin.Configuration {
    
    public partial class EditSiteHostHeaders {
        protected Xenosynth.Admin.Controls.MessageBox MessageBox1;
        protected Xenosynth.Admin.Configuration.SiteTabControl SiteTabControl1;
        protected System.Web.UI.WebControls.DataGrid DataGridHostHeaders;
        protected Fluent.EmptyRepeaterPanel.EmptyRepeaterPanel Emptyrepeaterpanel1;
        protected System.Web.UI.WebControls.LinkButton ButtonSave;
        protected System.Web.UI.WebControls.TextBox TextBoxHostHeader;
        protected System.Web.UI.WebControls.Button Button1;
        protected System.Web.UI.WebControls.Button Button2;
    }
}
