// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace Xenosynth.Admin.Configuration {
	
	
	public partial class EditWebPart {
		
		protected System.Web.UI.WebControls.Content Content2;
		
		protected Xenosynth.Admin.Configuration.WebPartTasks SiteTasks1;
		
		protected System.Web.UI.WebControls.Content Content1;
		
		protected Xenosynth.Admin.Controls.PathBrowser PathBrowser1;
		
		protected Xenosynth.Admin.Controls.MessageBox MessageBox1;
		
		protected System.Web.UI.WebControls.TextBox TextBoxTitle;
		
		protected System.Web.UI.WebControls.RequiredFieldValidator Requiredfieldvalidator1;
		
		protected System.Web.UI.WebControls.TextBox TextBoxDescription;
		
		protected System.Web.UI.WebControls.TextBox TextBoxDescriptionCount;
		
		protected Fluent.MultiLineTextBoxValidator Multilinetextboxvalidator1;
		
		protected System.Web.UI.WebControls.TextBox TextBoxImageUrl;
		
		protected System.Web.UI.WebControls.TextBox TextBoxClassName;
		
		protected System.Web.UI.WebControls.TextBox TextBoxUrl;
		
		protected System.Web.UI.WebControls.Button Button1;
		
		protected System.Web.UI.WebControls.Button Button2;
		
		protected Fluent.DataBinding.DataBindingManager DataBindingManagerWebPart;
	}
}
