//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Xenosynth.Admin.Configuration {
    
    public partial class EditHostHeader {
        
        protected System.Web.UI.HtmlControls.HtmlForm Form1;
        protected Fluent.Presentation.Template TemplateLayout1;
        protected Fluent.Presentation.TemplateSection Side;
        protected Fluent.Presentation.TemplateSection Main;
        protected System.Web.UI.WebControls.TextBox TextBoxHostHeader;
        protected System.Web.UI.WebControls.RequiredFieldValidator Requiredfieldvalidator1;
        protected System.Web.UI.WebControls.DropDownList DropDownListDirectories;
        protected System.Web.UI.WebControls.RequiredFieldValidator Requiredfieldvalidator2;
        protected System.Web.UI.WebControls.Button Button1;
        protected Fluent.DataBinding.DataBindingManager DataBindingManagerHostHeader;
    }
}
