// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace Xenosynth.Admin.Configuration {
	
	
	public partial class Settings {
		
		protected Xenosynth.Admin.Controls.MessageBox MessageBox1;
		
		protected Xenosynth.Admin.Configuration.SettingsTabControl SettingsTabControl1;
		
		protected System.Web.UI.WebControls.DataGrid DataGridSettings;
		
		protected Xenosynth.Admin.Configuration.ConfigurationSettingEditor ConfigurationSettingEditor;
		
		protected System.Web.UI.WebControls.LinkButton DeleteButton;
		
		protected Fluent.AlertButton Alertbutton1;
		
		protected System.Web.UI.WebControls.LinkButton ButtonSave;
	}
}
