// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace Xenosynth.Admin.Configuration {
	
	
	public partial class Sites {
		
		protected System.Web.UI.WebControls.Content Content2;
		
		protected System.Web.UI.WebControls.Content Content1;
		
		protected System.Web.UI.WebControls.DataGrid DataGridSites;
		
		protected System.Web.UI.WebControls.HyperLink Hyperlink1;
		
		protected System.Web.UI.WebControls.HyperLink Hyperlink2;
		
		protected System.Web.UI.WebControls.LinkButton DeleteSiteButton;
		
		protected Fluent.AlertButton Alertbutton1;
		
		protected Fluent.EmptyRepeaterPanel.EmptyRepeaterPanel Emptyrepeaterpanel1;
	}
}
