//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Xenosynth.Admin.Configuration {
    
    public partial class WebParts {
        protected Xenosynth.Admin.Configuration.WebPartTasks WebPartTasks1;
        protected System.Web.UI.WebControls.DataGrid DataGridWebParts;
        protected Fluent.EmptyRepeaterPanel.EmptyRepeaterPanel Emptyrepeaterpanel1;
    }
}
