//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Xenosynth.Admin.Controls.WebParts {
    
    public partial class RecentFileList {
        protected System.Web.UI.WebControls.DataGrid DataGridRecentFiles;
        protected Fluent.EmptyRepeaterPanel.EmptyRepeaterPanel EmptyRepeaterPanel1;
    }
}
