// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace Xenosynth.Admin.Modules {
	
	
	public partial class _Default {
		
		protected Xenosynth.Admin.Modules.ModuleTasks ModuleTasks1;
		
		protected System.Web.UI.WebControls.DataGrid DataGridModules;
	}
}
