//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Xenosynth.Admin.Content.TemplateGallery {
    
    public partial class EditTemplateContentBlocks {
        protected Xenosynth.Admin.Content.PathBrowser PathBrowser1;
        protected Xenosynth.Admin.Controls.MessageBox MessageBox1;
        protected Xenosynth.Admin.Content.TemplateGallery.TemplateTabControl TemplateTabControl1;
        protected System.Web.UI.WebControls.DataGrid DataGridRegisteredContent;
        protected Fluent.EmptyRepeaterPanel.EmptyRepeaterPanel Emptyrepeaterpanel1;
        protected System.Web.UI.WebControls.TextBox TextBoxControlID;
        protected System.Web.UI.WebControls.DropDownList DropDownListContentType;
        protected System.Web.UI.WebControls.Button Button3;
        protected System.Web.UI.WebControls.Button Button4;
        protected Fluent.DataBinding.DataBindingManager DataBindingRegisteredContent;
    }
}
