// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace Xenosynth.Admin {
	
	
	public partial class Default {
		
		protected System.Web.UI.HtmlControls.HtmlForm form1;
		
		protected System.Web.UI.ScriptManager MasterScriptManager;
		
		protected System.Web.UI.WebControls.LinkButton LinkButtonLogOut;
		
		protected Fluent.Navigation.TabControl TabControlNavigationMain;
		
		protected Fluent.Navigation.TabControl TabControlNavigationSub;
		
		protected System.Web.UI.WebControls.ContentPlaceHolder Main;
		
		protected System.Web.UI.WebControls.ContentPlaceHolder Side;
	}
}
