//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Xenosynth.Admin {
    
    public partial class _Default {
        protected System.Web.UI.WebControls.WebParts.WebPartManager WebPartManager1;
        protected System.Web.UI.WebControls.LinkButton LinkButton1;
        protected System.Web.UI.WebControls.LinkButton LinkButtonEdit;
        protected System.Web.UI.WebControls.LinkButton LinkButtonCatalog;
        protected System.Web.UI.WebControls.WebParts.CatalogZone CatalogZone1;
        protected Xenosynth.Admin.Controls.WebParts.RegisteredCatalogZone RegisteredCatalogZone1;
        protected System.Web.UI.WebControls.WebParts.PageCatalogPart PageCatalogPart1;
        protected System.Web.UI.WebControls.WebParts.EditorZone EditorZone;
        protected System.Web.UI.WebControls.WebParts.AppearanceEditorPart AppearanceEditorPart1;
        protected System.Web.UI.WebControls.WebParts.BehaviorEditorPart BehaviorEditorPart1;
        protected System.Web.UI.WebControls.WebParts.LayoutEditorPart LayoutEditorPart1;
        protected System.Web.UI.WebControls.WebParts.PropertyGridEditorPart PropertyGridEditorPart1;
        protected System.Web.UI.WebControls.WebParts.WebPartZone WebPartZoneLeft;
        protected System.Web.UI.WebControls.WebParts.WebPartZone WebPartZoneRight;
    }
}
