// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace Xenosynth.Admin {
	
	
	public partial class ForgotPassword {
		
		protected System.Web.UI.HtmlControls.HtmlHead HEAD1;
		
		protected System.Web.UI.HtmlControls.HtmlForm Form1;
		
		protected System.Web.UI.WebControls.TextBox Username;
		
		protected Fluent.ControlFocus.ControlFocus ControlFocus1;
		
		protected System.Web.UI.WebControls.Button Submit;
		
		protected Fluent.AutoPostBack AutoPostBack1;
		
		protected System.Web.UI.WebControls.Label FailureText;
	}
}
