//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Xenosynth.Admin.Content {
    
    public partial class AddPage {
        protected System.Web.UI.WebControls.TextBox TextBoxFileName;
        protected System.Web.UI.WebControls.RegularExpressionValidator RegularExpressionValidatorFileName;
        protected System.Web.UI.WebControls.TextBox TextBoxTitle;
        protected System.Web.UI.WebControls.RequiredFieldValidator Requiredfieldvalidator1;
        protected System.Web.UI.WebControls.DropDownList DropDownListTemplates;
        protected System.Web.UI.WebControls.RequiredFieldValidator Requiredfieldvalidator2;
        protected System.Web.UI.WebControls.TextBox TextBoxDescription;
        protected System.Web.UI.WebControls.TextBox TextBoxDescriptionCount;
        protected Fluent.MultiLineTextBoxValidator Multilinetextboxvalidator1;
        protected System.Web.UI.WebControls.TextBox TextBoxKeywords;
        protected System.Web.UI.WebControls.TextBox TextBoxKeywordsCount;
        protected Fluent.MultiLineTextBoxValidator Multilinetextboxvalidator2;
        protected System.Web.UI.WebControls.CheckBox CheckBoxIsHidden;
        protected Fluent.DataBinding.DataBindingManager DataBindingManagerPage;
    }
}
