//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Xenosynth.Admin.Content.Page {
    
    public partial class EditPagePublishing {
        protected Xenosynth.Admin.Content.PathBrowser PathBrowser1;
        protected Xenosynth.Admin.Controls.MessageBox MessageBox1;
        protected Xenosynth.Admin.Content.Page.PageTabControl PageTabControl1;
        protected System.Web.UI.UpdatePanel UpdatePanelPublishStart;
        protected System.Web.UI.WebControls.TextBox TextBoxPublishStart;
        protected Xenosynth.Admin.Controls.PopupCalendar PopupCalendar1;
        protected System.Web.UI.UpdatePanel UpdatePanelPublishEnd;
        protected System.Web.UI.WebControls.TextBox TextBoxPublishEnd;
        protected Xenosynth.Admin.Controls.PopupCalendar PopupCalendar2;
        protected System.Web.UI.WebControls.Button Button1;
        protected System.Web.UI.WebControls.Button Button2;
        protected Fluent.DataBinding.DataBindingManager DataBindingManagerPage;
        protected Xenosynth.Admin.Content.PageTasks Pagetasks1;
    }
}
