//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Xenosynth.Admin.Content.ImageGallery {
    
    public partial class AddGallery {
        protected Xenosynth.Admin.Content.SearchFiles SearchFiles1;
        protected Xenosynth.Admin.Content.PathBrowser PathBrowser1;
        protected System.Web.UI.WebControls.TextBox TextBoxFileName;
        protected System.Web.UI.WebControls.RequiredFieldValidator RequiredFieldValidator1;
        protected System.Web.UI.WebControls.TextBox TextBoxTitle;
        protected System.Web.UI.WebControls.RequiredFieldValidator RequiredFieldValidator2;
        protected System.Web.UI.WebControls.TextBox TextBoxDescription;
        protected System.Web.UI.WebControls.TextBox TextBoxDescriptionCount;
        protected Fluent.MultiLineTextBoxValidator Multilinetextboxvalidator1;
        protected System.Web.UI.WebControls.CheckBox CheckBoxIsHidden;
        protected System.Web.UI.WebControls.Button Button1;
        protected System.Web.UI.WebControls.Button Button2;
        protected Fluent.DataBinding.DataBindingManager DataBindingManagerGallery;
    }
}
