//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Xenosynth.Admin.Content.ImageGallery {
    
    public partial class EditImage {
        protected Xenosynth.Admin.Content.ImageGallery.ImageTasks ImageTasks1;
        protected Xenosynth.Admin.Content.ImageGallery.ImageGalleryTasks ImageGalleryTasks1;
        protected Xenosynth.Admin.Content.PathBrowser PathBrowser1;
        protected Xenosynth.Admin.Controls.MessageBox MessageBox1;
        protected Xenosynth.Admin.Content.ImageGallery.ImageTabControl ImageTabControl1;
        protected System.Web.UI.WebControls.TextBox TextBoxFileName;
        protected System.Web.UI.WebControls.TextBox TextBoxTitle;
        protected System.Web.UI.WebControls.TextBox TextBoxAltText;
        protected System.Web.UI.WebControls.TextBox TextBoxDescription;
        protected System.Web.UI.WebControls.TextBox TextBoxDescriptionCount;
        protected Fluent.MultiLineTextBoxValidator Multilinetextboxvalidator1;
        protected System.Web.UI.WebControls.TextBox TextBoxKeywords;
        protected System.Web.UI.WebControls.TextBox TextBoxKeywordsCount;
        protected Fluent.MultiLineTextBoxValidator Multilinetextboxvalidator2;
        protected System.Web.UI.WebControls.TextBox TextBoxDateCreated;
        protected System.Web.UI.WebControls.TextBox TextBoxDateModified;
        protected System.Web.UI.WebControls.TextBox TextBoxVersion;
        protected System.Web.UI.WebControls.TextBox TextBoxStatus;
        protected System.Web.UI.WebControls.TextBox TextBoxFullPath;
        protected System.Web.UI.WebControls.Button Button1;
        protected System.Web.UI.WebControls.Button Button2;
        protected Fluent.DataBinding.DataBindingManager DataBindingManagerImage;
    }
}
