//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Xenosynth.Admin.Content.ImageGallery {
    
    public partial class ViewImageSizes {
        protected Xenosynth.Admin.Content.PathBrowser PathBrowser1;
        protected Xenosynth.Admin.Controls.MessageBox MessageBox1;
        protected Xenosynth.Admin.Content.ImageGallery.ImageTabControl ImageTabControl1;
        protected Fluent.Navigation.TabControl TabControlImageSizes;
        protected Xenosynth.Admin.Content.ImageGallery.ImageTasks ImageTasks1;
        protected Xenosynth.Admin.Content.ImageGallery.ImageGalleryTasks ImageGalleryTasks1;
    }
}
