//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Xenosynth.Admin.Content.ImageGallery {
    
    
    /// <summary>
    /// ViewImageHistory class.
    /// </summary>
    /// <remarks>
    /// Auto-generated class.
    /// </remarks>
    public partial class ViewImageHistory {
        
        /// <summary>
        /// PathBrowser1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Xenosynth.Admin.Content.PathBrowser PathBrowser1;
        
        /// <summary>
        /// MessageBox1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.UserControl MessageBox1;
        
        /// <summary>
        /// ImageTabControl1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Xenosynth.Admin.Content.ImageGallery.ImageTabControl ImageTabControl1;
        
        /// <summary>
        /// ViewFileHistory1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Xenosynth.Modules.Cms.Admin.Controls.ViewFileHistory ViewFileHistory1;
        
        /// <summary>
        /// ImageTasks1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Xenosynth.Admin.Content.ImageGallery.ImageTasks ImageTasks1;
        
        /// <summary>
        /// ImageGalleryTasks1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Xenosynth.Admin.Content.ImageGallery.ImageGalleryTasks ImageGalleryTasks1;
    }
}
