//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Xenosynth.Admin.Content.ImageGallery {
    
    public partial class ViewImageRevisions {
        protected Xenosynth.Admin.Content.PathBrowser PathBrowser1;
        protected System.Web.UI.UserControl MessageBox1;
        protected Xenosynth.Admin.Content.ImageGallery.ImageTabControl ImageTabControl1;
        protected System.Web.UI.WebControls.DataGrid DataGridRevisionHistory;
        protected Fluent.EmptyRepeaterPanel.EmptyRepeaterPanel Emptyrepeaterpanel2;
        protected Xenosynth.Admin.Content.ImageGallery.ImageTasks ImageTasks1;
        protected Xenosynth.Admin.Content.ImageGallery.ImageGalleryTasks ImageGalleryTasks1;
    }
}
