//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Xenosynth.Admin.Content {
    
    public partial class AddDirectory {
        protected Xenosynth.Admin.Content.PathBrowser PathBrowser1;
        protected Xenosynth.Admin.Content.DirectoryTabControl DirectoryTabControl1;
        protected System.Web.UI.WebControls.TextBox TextBoxFileName;
        protected System.Web.UI.WebControls.RequiredFieldValidator RequiredFieldValidator1;
        protected System.Web.UI.WebControls.TextBox TextBoxTitle;
        protected System.Web.UI.WebControls.RequiredFieldValidator RequiredFieldValidator2;
        protected System.Web.UI.WebControls.DropDownList DropDownListTemplateGalleries;
        protected System.Web.UI.WebControls.DropDownList DropDownListImageGalleries;
        protected System.Web.UI.WebControls.CheckBox CheckBoxIsHidden;
        protected System.Web.UI.WebControls.Button Button1;
        protected Fluent.DataBinding.DataBindingManager DataBindingManagerDirectory;
    }
}
